# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: copilot.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcopilot.proto\"d\n\x07Message\x12\x1b\n\x04role\x18\x01 \x01(\x0e\x32\r.Message.Role\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"+\n\x04Role\x12\n\n\x06SYSTEM\x10\x00\x12\x08\n\x04USER\x10\x01\x12\r\n\tASSISTANT\x10\x02\"\"\n\x04\x43hat\x12\x1a\n\x08messages\x18\x01 \x03(\x0b\x32\x08.Message\"\x1b\n\x0bStringChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t29\n\x07\x43opilot\x12.\n\x13GenerateIntegration\x12\x05.Chat\x1a\x0c.StringChunk\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'copilot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=17
  _globals['_MESSAGE']._serialized_end=117
  _globals['_MESSAGE_ROLE']._serialized_start=74
  _globals['_MESSAGE_ROLE']._serialized_end=117
  _globals['_CHAT']._serialized_start=119
  _globals['_CHAT']._serialized_end=153
  _globals['_STRINGCHUNK']._serialized_start=155
  _globals['_STRINGCHUNK']._serialized_end=182
  _globals['_COPILOT']._serialized_start=184
  _globals['_COPILOT']._serialized_end=241
# @@protoc_insertion_point(module_scope)
