# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import copilot_pb2 as copilot__pb2


class CopilotStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateIntegration = channel.unary_stream(
                '/Copilot/GenerateIntegration',
                request_serializer=copilot__pb2.Chat.SerializeToString,
                response_deserializer=copilot__pb2.StringChunk.FromString,
                )


class CopilotServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateIntegration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CopilotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateIntegration': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateIntegration,
                    request_deserializer=copilot__pb2.Chat.FromString,
                    response_serializer=copilot__pb2.StringChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Copilot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Copilot(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateIntegration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Copilot/GenerateIntegration',
            copilot__pb2.Chat.SerializeToString,
            copilot__pb2.StringChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
