[copilot]
model = "gpt-4-turbo-preview"
temperature = 0.3
seed = -1

[llm.codegen_chat]
model = "gpt-4-turbo-preview"
temperature = 0

[llm.q_gen]
model = "gpt-4-turbo-preview"
temperature = 0

[llm.copilot_chat]
model = "gpt-4-turbo-preview"
temperature = 0.7

[llm.artifact_edit_chat]
model = "gpt-4-turbo-preview"
temperature = 0.7
